### ISSUE TITLE
Line graph not displaying correctly.

### ISSUE THREAD

**Issue by russorat** [influxdata/giraffe#104] opened 2019-08-15 16:30 UTC
![Kapture 2019-08-15 at 9 28 11](https://user-images.githubusercontent.com/4805997/63110001-4a2fc400-bf3f-11e9-9d5a-c5df20a0d27f.gif)

[2019-08-15-09-18_chronograf_data.csv.zip](https://github.com/influxdata/giraffe/files/3506344/2019-08-15-09-18_chronograf_data.csv.zip)

```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "iexapis")
  |> filter(fn: (r) => r.host == "bigsur.prod")
  |> filter(fn: (r) => if v.ticker_symbol == "*" then false
                       else r._field == "latestPrice")
  |> filter(fn: (r) => r._field != "latestTime")
  |> filter(fn: (r) => if v.ticker_symbol == "*" then true
                       else r.symbol == v.ticker_symbol)
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
  |> drop(columns: ["host", "calculationPrice", "latestSource","_start","_stop"])
  |> yield(name: "latestPrice")
  
  
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "iexapis")
  |> filter(fn: (r) => r.host == "bigsur.prod")
  |> filter(fn: (r) => if v.ticker_symbol == "*" then r._field == "changePercent"
                       else false)
  |> filter(fn: (r) => r._field != "latestTime")
  |> map(fn: (r) => ({ r with _value: float(v:r._value) * 100.0 }))
  |> filter(fn: (r) => if v.ticker_symbol == "*" then true
                       else r.symbol == v.ticker_symbol)
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
  |> drop(columns: ["host", "calculationPrice", "latestSource","_start","_stop"])
  |> yield(name: "changePercent")
```

**Comment by chnn** [comment] 2019-08-16 15:16
Check out the first couple rows of the data:

```
_field      , _measurement , companyName , isUSMarketOpen , primaryExchange         , symbol , _value , _time
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 84.92  , 2019-08-15T14:20:00Z
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 84.725 , 2019-08-15T13:33:00Z
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 84.59  , 2019-08-15T13:34:00Z
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 84.27  , 2019-08-15T13:41:00Z
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 83.62  , 2019-08-15T13:42:00Z
latestPrice , iexapis      , Elastic NV  , true           , New York Stock Exchange , ESTC   , 84.49  , 2019-08-15T13:43:00Z
```

Giraffe draws lines between these points in the order it receives them. In this case the first point is at 14:20, but then the next point is at 13:33, so Giraffe draws a line between them.

A way to fix this in Flux is to add `|> sort(columns: ["_time"]` to your Flux query.

A way to fix it in Giraffe would be to add this feature: https://github.com/influxdata/giraffe/issues/29

I think this would be a useful addition, and sane defaults for line layers (sort by x axis) would prevent confusing cases like this one.

**Comment by chnn** [comment] 2019-08-16 17:51
Closing this because I think it's expected behavior, but I do want to get to #29!

**Closed by chnn** 2019-08-16 17:51 UTC
Labels: kind/bug
