### ISSUE TITLE
Render a Static Legend

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#342] opened 2020-10-29 22:06 UTC
### Background
We currently render a tooltip on hover as the main means of providing context and meaning to graph. This isn't useful for people who put dashboards on walls and it won't be usable if we provide mobile-viewing capability.

As a user, I want to be able to see a static legend on the graph so that I don't have to hover over a small line to get context.

### Use Case

- User can understand the visualization without mouse interaction

### Acceptance Criteria

- User can specify position of static legend (left, bottom, or right)
- User can specify sort in static legend (ex: alphabetical, ascending by `_value`, descending by `_value`) etc
- User can hover over an item in static legend and "focus" on that line
- User can click an item to "select" it, which fades out all other lines
  - User can `shift+click` or `meta+click` to add/remove lines from the selection

### Design Mockup:

[Giraffe / Static Legend](https://www.figma.com/file/6pwGOv5jyMT2rpU8ugZNM1/Static-Legend?node-id=0%3A1)

**Comment by 121watts** [comment] 2020-11-02 18:14
Just the giraffe work.  Not to be exposed yet in influxdata/ui.

**Comment by rbetts** [comment] 2020-12-15 22:00
There's the "manager use case" too - where dashboards are screenshot copied and then put into slides. These are unreadable currently as there aren't visible legends.

**Comment by kristinarobinson** [comment] 2021-03-22 16:52
Dupe of #492

**Closed by kristinarobinson** 2021-03-22 16:52 UTC
Labels: kind/feature request, team/bonitoo, team/ui
